/*
 * k8s.io/api/admission/v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1AdmissionReview : AdmissionReview describes an admission review request/response.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1AdmissionReview {
    /// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    #[serde(rename = "apiVersion", skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
    /// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    #[serde(rename = "request", skip_serializing_if = "Option::is_none")]
    pub request: Option<crate::models::V1AdmissionRequest>,
    #[serde(rename = "response", skip_serializing_if = "Option::is_none")]
    pub response: Option<crate::models::V1AdmissionResponse>,
}

impl V1AdmissionReview {
    /// AdmissionReview describes an admission review request/response.
    pub fn new() -> V1AdmissionReview {
        V1AdmissionReview {
            api_version: None,
            kind: None,
            request: None,
            response: None,
        }
    }
}


