/*
 * k8s.io/api/admission/v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1GroupVersionKind : GroupVersionKind unambiguously identifies a kind.  It doesn't anonymously include GroupVersion to avoid automatic coersion.  It doesn't use a GroupVersion to avoid custom marshalling



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1GroupVersionKind {
    #[serde(rename = "group")]
    pub group: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl V1GroupVersionKind {
    /// GroupVersionKind unambiguously identifies a kind.  It doesn't anonymously include GroupVersion to avoid automatic coersion.  It doesn't use a GroupVersion to avoid custom marshalling
    pub fn new(group: String, kind: String, version: String) -> V1GroupVersionKind {
        V1GroupVersionKind {
            group,
            kind,
            version,
        }
    }
}


