/*
 * k8s.io/api/admission/v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// V1GroupVersionResource : GroupVersionResource unambiguously identifies a resource.  It doesn't anonymously include GroupVersion to avoid automatic coersion.  It doesn't use a GroupVersion to avoid custom marshalling



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1GroupVersionResource {
    #[serde(rename = "group")]
    pub group: String,
    #[serde(rename = "resource")]
    pub resource: String,
    #[serde(rename = "version")]
    pub version: String,
}

impl V1GroupVersionResource {
    /// GroupVersionResource unambiguously identifies a resource.  It doesn't anonymously include GroupVersion to avoid automatic coersion.  It doesn't use a GroupVersion to avoid custom marshalling
    pub fn new(group: String, resource: String, version: String) -> V1GroupVersionResource {
        V1GroupVersionResource {
            group,
            resource,
            version,
        }
    }
}


